sudo: false
language: go
git:
    depth: 1
install: go get -v github.com/gohugoio/hugo
script:
    hugo
deploy:
    provider: pages
    skip_cleanup: true
    github_token: $Github_token_travis
    on:
        branch: master
    local_dir: public
    repo: zhu-wenjun/zhu-wenjun.github.io
    #fqdn: <custom-domain-if-needed>
    target_branch: master
    email: mason.wenjun.zhu@gmail.com
    name: zhu-wenjun
